import { IHeader } from "../../../../components/CustomTable/interfaces";

export const headers: Array<IHeader> = [
    {
      title: "User ID",
      name: "id",
      align: "left",
      headerAlign: "left",
      sortName: "id",
      width: "15%",
    },
    {
      title: "User Name",
      name: "name",
      align: "left",
      headerAlign: "left",
      sortName: "name",
      width: "25%",
    },
    {
      title: "User Age",
      name: "age",
      align: "left",
      headerAlign: "left",
      sortName: "age",
      width: "15%",
    },
    {
      title: "User Address",
      name: "address",
      align: "left",
      headerAlign: "left",
      sortName: "address",
      width: "45%",
    },
  ]

export const data = [
  {
    id: 1,
    name: 'John Smith',
    age: 32,
    address: 'New York No. 1 Lake Park',
  },
  {
    id: 2,
    name: 'Jim Green',
    age: 42,
    address: 'London No. 1 Lake Park',
  },
  {
    id: 3,
    name: 'Joe Black',
    age: 32,
    address: 'Sidney No. 1 Lake Park',
  },
  {
    id: 4,
    name: 'Jim Red',
    age: 32,
    address: 'London No. 2 Lake Park',
  },


]

// export const data = [
//   {
//     Virksomhed: "Sampension",
//     IOS_score: "4.5",
//     IOS_Ratings: "87",
//     Play_score: "4.1",
//     Play_Ratings: "51",
//     current_Vaegtet_pr: "4.3",
//     current_Sum_pr: "138",
//     Vaegtet_pr: "4.3",
//     Sum_pr: "137",
//   },
//   {
//     Virksomhed: "PFA",
//     IOS_score: "4.1",
//     IOS_Ratings: "4300",
//     Play_score: "3.0",
//     Play_Ratings: "247",
//     current_Vaegtet_pr: "4.0",
//     current_Sum_pr: "4547",
//     Vaegtet_pr: "4.0",
//     Sum_pr: "4347",
//   },
//   {
//     Virksomhed: "Industriens Pension",
//     IOS_score: "3.4",
//     IOS_Ratings: "55",
//     Play_score: "3.6",
//     Play_Ratings: "317",
//     current_Vaegtet_pr: "3.6",
//     current_Sum_pr: "372",
//     Vaegtet_pr: "3.6",
//     Sum_pr: "366",
//   },
//   {
//     Virksomhed: "Grandhood",
//     IOS_score: "3.4",
//     IOS_Ratings: "14",
//     Play_score: "0.0",
//     Play_Ratings: "0",
//     current_Vaegtet_pr: "3.4",
//     current_Sum_pr: "14",
//     Vaegtet_pr: "3.4",
//     Sum_pr: "14",
//   },
//   {
//     Virksomhed: "AP Pension",
//     IOS_score: "2.3",
//     IOS_Ratings: "13",
//     Play_score: "3.6",
//     Play_Ratings: "44",
//     current_Vaegtet_pr: "3.3",
//     current_Sum_pr: "57",
//     Vaegtet_pr: "3.4",
//     Sum_pr: "49",
//   },
//   {
//     Virksomhed: "Danica Pension",
//     IOS_score: "4.1",
//     IOS_Ratings: "347",
//     Play_score: "2.2",
//     Play_Ratings: "256",
//     current_Vaegtet_pr: "3.3",
//     current_Sum_pr: "603",
//     Vaegtet_pr: "3.2",
//     Sum_pr: "578",
//   },
//   {
//     Virksomhed: "PensionDanmark",
//     IOS_score: "2.5",
//     IOS_Ratings: "45",
//     Play_score: "3.3",
//     Play_Ratings: "155",
//     current_Vaegtet_pr: "3.1",
//     current_Sum_pr: "200",
//     Vaegtet_pr: "3.0",
//     Sum_pr: "196",
//   },
//   {
//     Virksomhed: "Velliv",
//     IOS_score: "1.0",
//     IOS_Ratings: "0",
//     Play_score: "1.6",
//     Play_Ratings: "223",
//     current_Vaegtet_pr: "1.6",
//     current_Sum_pr: "223",
//     Vaegtet_pr: "1.7",
//     Sum_pr: "438",
//   },
//   {
//     Virksomhed: "PKA",
//     IOS_score: "1.0",
//     IOS_Ratings: "1",
//     Play_score: "1.3",
//     Play_Ratings: "69",
//     current_Vaegtet_pr: "1.3",
//     current_Sum_pr: "70",
//     Vaegtet_pr: "1.2",
//     Sum_pr: "69",
//   }
// ];
